analyze -library WORK -format vhdl ../../vhd/000-globals.vhd
analyze -library WORK -format vhdl ../../vhd/a.b-DATAPATH.core/a.b.c-EXECUTE.core/a.b.c.a-ALU.core/a.b.c.a.a-LU_CTRL.vhd
analyze -library WORK -format vhdl ../../vhd/a.b-DATAPATH.core/a.b.c-EXECUTE.core/a.b.c.a-ALU.core/a.b.c.a.b-LOGIC_UNIT.vhd
analyze -library WORK -format vhdl ../../vhd/a.b-DATAPATH.core/a.b.c-EXECUTE.core/a.b.c.a-ALU.core/a.b.c.a.b-ADD_SUB.vhd
analyze -library WORK -format vhdl ../../vhd/a.b-DATAPATH.core/a.b.c-EXECUTE.core/a.b.c.a-ALU.core/a.b.c.a.d-SHIFTER.vhd
analyze -library WORK -format vhdl ../../vhd/a.b-DATAPATH.core/a.b.c-EXECUTE.core/a.b.c.a-ALU.core/a.b.c.a.e-COMPARATOR.vhd
analyze -library WORK -format vhdl ../../vhd/a.b-DATAPATH.core/a.b.c-EXECUTE.core/a.b.c.a-ALU.core/a.b.c.a.f-ZERO_DETECTOR.vhd
analyze -library WORK -format vhdl ../../vhd/a.b-DATAPATH.core/a.b.c-EXECUTE.core/a.b.c.a-ALU.vhd
